version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - db_host=db
      - redis_host=redis
  redis:
    image: "redis:7.0.2-bullseye"
  db:
    image: "postgres:14.4"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${db_password}"
      POSTGRES_USER: "${db_user}"
      POSTGRES_DB: "${db_name}"